sudo: required
services:
    - docker

before_install:
    - docker build -t dwilbank/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dwilbank/docker-react npm run test -- --watchAll=false