sudo: required
services:
    - docker

before_install:
    - docker build -t dwilbank/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true dwilbank/docker-react npm run test -- --watchAll=false

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    name: "wilbanks-docker-react"
    env: "WilbanksDockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-1-073892902142"
    bucket_path: "wilbanks-docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"